name: Update Galaxy Version

on:
  push:
    branches: [main]  # Or release event for post-release bumps

permissions:
  contents: write  # Needed for git commit/push

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute next version for galaxy.yaml
        id: compute
        run: |
          chmod +x update-galaxy.sh
          ./update-galaxy.sh

      - name: Update galaxy.yaml with new version if major update
      - if: "${{ steps.compute.outputs.bump_type}} == minor"
      # Replace next_version_plain with next_expected_release?
        run: |
          new_version="${{ steps.compute.outputs.next_version_plain }}" 
          sed -i "s/version: [0-9]\+\.[0-9]\+\.[0-9]\+/version: $new_version/" galaxy.yaml

      - name: Update galaxy.yaml with new version if minor update
      - if: "${{ steps.compute.outputs.bump_type}} == patch"
      # Replace next_version_plain with next_expected_release?
        run: |
          new_version="${{ steps.compute.outputs.next_version_plain }}" 
          sed -i "s/version: [0-9]\+\.[0-9]\+\.[0-9]\+/version: $new_version/" galaxy.yaml

      - name: Commit and push updated galaxy.yaml
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add galaxy.yaml
          git diff --staged --quiet || git commit -m "Bump galaxy.yaml version to ${{ steps.compute.outputs.next_version_plain }} [skip ci]"
          git push 
# I need to define a branch in git push, either master or release branch, because I didn't make it clear?